spring:
  application:
    name: api-gateway-svc
  cloud:
    gateway:
      routes[0]:
        id: discovery-service
        uri: http://eureka-0.eureka:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[1]:
        id: discovery-service-resources
        uri: http://eureka-0.eureka:8761
        predicates[0]: Path=/eureka/**
      routes[2]:
        id: hotel-user-service
        uri: http://hotel-service-svc:8082
        predicates[0]: Path=/user-api/**
      routes[3]:
        id: hotel-room-service
        uri: http://hotel-service-svc:8082
        predicates[0]: Path=/room-api/**
      routes[4]:
        id: auth-login-service
        uri: http://auth-service-svc:8085
        predicates[0]: Path=/login
      routes[5]:
        id: auth-register-service
        uri: http://auth-service-svc:8085
        predicates[0]: Path=/register
      routes[6]:
        id: hotel-booking-service
        uri: http://hotel-service-svc:8082
        predicates[0]: Path=/booking-api/**
      routes[7]:
        id: auth-token-service
        uri: http://auth-service-svc
        predicates[0]: Path=/token/**

# eureka:
#   client:
#     service-url:
#       defaultZone: http://eureka-0.eureka:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO
