spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: hotel-user-service
        uri: lb://hotel-service
        predicates[0]: Path=/user-api/**
      routes[1]:
        id: hotel-room-service
        uri: lb://hotel-service
        predicates[0]: Path=/room-api/**
      routes[2]:
        id: discovery-service
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[3]:
        id: discovery-service-resources
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO
