spring:
  application:
    name: booking-service-api
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8087
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-0.eureka:8761/eureka
