apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: dkrgn/notification-service-img:latest
          ports:
            - containerPort: 8086
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pg-notification-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pg-notification-config
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-notification-secrets
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-notification-secrets
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
