server:
  port: 8083
spring:
  application:
    name: room-service-svc
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:5435/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-0.eureka:8761/eureka