server:
  port: 0
spring:
  application:
    name: room-service
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/rooms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka