server:
    port: 8084
spring:
    application:
        name: payment-service-svc
    datasource:
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        url: jdbc:postgresql://${DB_HOST}:5434/${DB_NAME}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
#eureka:
#    client:
#        service-url:
#            defaultZone: http://eureka-0.eureka:8761/eureka