server:
    port: 8083
spring:
    application:
        name: payment-service
    datasource:
        username: postgres
        password:
        url: jdbc:postgresql://localhost:5432/payments
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka