server:
    port: 0
spring:
    application:
        name: payment-service
    datasource:
        username: postgres
        password: password
        url: jdbc:postgresql://postgres:5434/payments
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
eureka:
    client:
        service-url:
            defaultZone: http://eureka:password@discovery-service:8761/eureka/