apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: dkrgn/auth-service-img:latest
          ports:
            - containerPort: 8085
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pg-auth-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pg-auth-config
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-auth-secrets
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-auth-secrets
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
