apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: dkrgn/room-service-img:latest
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pg-room-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pg-room-config
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-room-secrets
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-room-secrets
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: room-service-svc
spec:
  selector:
    app: room-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
