apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: dkrgn/payment-service-img:latest
          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pg-payment-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pg-payment-config
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-payment-secrets
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-payment-secrets
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
